export const keyMap: { [key: string] : string } = {
    a: 'p', A: 'P',
    b: 'q', B: 'Q',
    c: 'r', C: 'R',
    d: 's', D: 'S',
    e: 't', E: 'T',
    f: 'u', F: 'U',
    g: 'v', G: 'V',
    h: 'w', H: 'W',
    i: 'x', I: 'X',
    j: 'y', J: 'Y',
    k: 'z', K: 'Z',
    l: 'a', L: 'A',
    m: 'b', M: 'B',
    n: 'c', N: 'C',
    o: 'd', O: 'D',
    p: 'e', P: 'E',
    q: 'f', Q: 'F',
    r: 'g', R: 'G',
    s: 'h', S: 'H',
    t: 'i', T: 'I',
    u: 'j', U: 'J',
    v: 'k', V: 'K',
    w: 'l', W: 'L',
    x: 'm', X: 'M',
    y: 'n', Y: 'N',
    z: 'o', Z: 'O',
};